# Generated by Django 5.1.4 on 2025-07-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.DeleteModel(
            name='CourseView',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
